import { MenuItem, AddOn } from "./types";

export const MENU_ITEMS: MenuItem[] = [
  // Coffee
  {
    name: "Americano",
    category: "coffee",
    prices: { small: 3.0, large: 4.0 },
    canBeHot: true,
    canBeIced: true,
    hasMilk: false,
    canAddEspresso: true,
    canAddMatcha: false,
    canCustomize: true,
  },
  {
    name: "Latte",
    category: "coffee",
    prices: { small: 4.0, large: 5.0 },
    canBeHot: true,
    canBeIced: true,
    hasMilk: true,
    canAddEspresso: true,
    canAddMatcha: false,
    canCustomize: true,
  },
  {
    name: "Cold Brew",
    category: "coffee",
    prices: { small: 4.0, large: 5.0 },
    canBeHot: false,
    canBeIced: true,
    hasMilk: false,
    canAddEspresso: true,
    canAddMatcha: false,
    canCustomize: true,
  },
  {
    name: "Mocha",
    category: "coffee",
    prices: { small: 4.5, large: 5.5 },
    canBeHot: true,
    canBeIced: true,
    hasMilk: true,
    canAddEspresso: true,
    canAddMatcha: false,
    canCustomize: true,
  },
  {
    name: "Coffee Frappuccino",
    category: "coffee",
    prices: { small: 5.5, large: 6.0 },
    canBeHot: false,
    canBeIced: true,
    hasMilk: true,
    canAddEspresso: true,
    canAddMatcha: false,
    canCustomize: true,
  },
  // Tea
  {
    name: "Black Tea",
    category: "tea",
    prices: { small: 3.0, large: 3.75 },
    canBeHot: true,
    canBeIced: true,
    hasMilk: false,
    canAddEspresso: false,
    canAddMatcha: false,
    canCustomize: true,
  },
  {
    name: "Jasmine Tea",
    category: "tea",
    prices: { small: 3.0, large: 3.75 },
    canBeHot: true,
    canBeIced: true,
    hasMilk: false,
    canAddEspresso: false,
    canAddMatcha: false,
    canCustomize: true,
  },
  {
    name: "Lemon Green Tea",
    category: "tea",
    prices: { small: 3.5, large: 4.25 },
    canBeHot: true,
    canBeIced: true,
    hasMilk: false,
    canAddEspresso: false,
    canAddMatcha: false,
    canCustomize: true,
  },
  {
    name: "Matcha Latte",
    category: "tea",
    prices: { small: 4.5, large: 5.25 },
    canBeHot: true,
    canBeIced: true,
    hasMilk: true,
    canAddEspresso: false,
    canAddMatcha: true,
    canCustomize: true,
  },
  // Pastry
  {
    name: "Plain Croissant",
    category: "pastry",
    prices: { small: 3.5, large: 3.5 },
    canBeHot: false,
    canBeIced: false,
    hasMilk: false,
    canAddEspresso: false,
    canAddMatcha: false,
    canCustomize: false,
  },
  {
    name: "Chocolate Croissant",
    category: "pastry",
    prices: { small: 4.0, large: 4.0 },
    canBeHot: false,
    canBeIced: false,
    hasMilk: false,
    canAddEspresso: false,
    canAddMatcha: false,
    canCustomize: false,
  },
  {
    name: "Chocolate Chip Cookie",
    category: "pastry",
    prices: { small: 2.5, large: 2.5 },
    canBeHot: false,
    canBeIced: false,
    hasMilk: false,
    canAddEspresso: false,
    canAddMatcha: false,
    canCustomize: false,
  },
  {
    name: "Banana Bread",
    category: "pastry",
    prices: { small: 3.0, large: 3.0 },
    canBeHot: false,
    canBeIced: false,
    hasMilk: false,
    canAddEspresso: false,
    canAddMatcha: false,
    canCustomize: false,
  },
];

export const ADD_ONS: AddOn[] = [
  { name: "Whole Milk", price: 0.0, type: "milk" },
  { name: "Skim Milk", price: 0.0, type: "milk" },
  { name: "Oat Milk", price: 0.5, type: "milk" },
  { name: "Almond Milk", price: 0.75, type: "milk" },
  { name: "Extra Espresso Shot", price: 1.5, type: "shot" },
  { name: "Extra Matcha Shot", price: 1.5, type: "shot" },
  { name: "Caramel Syrup", price: 0.5, type: "syrup" },
  { name: "Hazelnut Syrup", price: 0.5, type: "syrup" },
];

export const SWEETNESS_LEVELS = [
  "no_sugar",
  "less_sugar",
  "normal",
  "extra_sugar",
] as const;

export const ICE_LEVELS = [
  "no_ice",
  "less_ice",
  "normal",
  "extra_ice",
] as const;

export const MAX_ESPRESSO_SHOTS = 6;
export const MAX_SYRUP_PUMPS = 6;
